### ISSUE TITLE
WaterBot is Non-Functional

### ISSUE THREAD

**Issue by Yagisan** [andyruwruw/stardew-valley-water-bot#1]
#### WaterBot version:
1.0.0

## Steps to reproduce
Attempt to water crops.

## Expected behavior
Crops are watered.

## Actual behavior
Unfortunately the WaterBot appears non-functional for me.

I made a video of it running [here](https://youtu.be/G1gVMWod3fU). You can see the bot go to each area, and fail to water. You can see that energy does not decrease, and no watering is done. Finally at the end, it gets stuck on the last tile to water. I am using the Copper Watering can, and the Grandpa's Farm custom farm from SVE.

You can get my SMAPI log [here](https://smapi.io/log/32610b3697be4358b475216e7835e841).

**Comment by andyruwruw** [comment]
Thank you for all the useful information.

I'll be honest, I've never actually purchased the Copper Watering Can (probably why I made the mod) so I need to do some testing with that. I'll try to recreate your situation from the video and get a patch out soon.

Thank you :)

**Comment by Yagisan** [comment]
As requested on Nexus, a screenshot of the whole farm is [here](https://ibb.co/ch1TkHx).

**Comment by andyruwruw** [comment]
I believe this to be resolved with 1.1.0, but let me know if some issues are still persisting. 😄
Thank you for being so helpful in figuring it out.

Check the [Change Log](https://github.com/andyruwruw/stardew-valley-water-bot/blob/main/CHANGELOG.md)
